server:
  port: 8088
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/payroll-service
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: employee-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/employees/**

        - id: payroll-calculation-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/payrolls/**

        - id: tax-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/taxes/**

        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/payments/**