spring.security.oauth2.client.registration.keycloak-client.provider=keycloak
spring.security.oauth2.client.registration.keycloak-client.client-id=payroll-service
spring.security.oauth2.client.registration.keycloak-client.client-secret=Atbdl5NyRgUUMnSGu40YdoJeLT6IfUwI
spring.security.oauth2.client.registration.keycloak-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak-client.scope=openid

spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8080/realms/payroll-service/protocol/openid-connect/token